language: ruby
script:
  - bundle exec mspec .
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - rbx-head
  - ree
jdk:
  - openjdk7
allow_failures:
 - rvm: ruby-head
 - rvm: jruby-head
 - rvm: rbx-head
notifications:
  recipients:
    - brixen@gmail.com
